# Generated by Django 3.1.5 on 2021-01-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/mumbai.jpg', null=True, upload_to=''),
        ),
    ]
