# Generated by Django 3.1.5 on 2021-01-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210122_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='mumbai.jpg', null=True, upload_to=''),
        ),
    ]
