# Generated by Django 3.1.5 on 2021-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210122_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/mumbai.jpg', null=True, upload_to=''),
        ),
    ]
